model:
    base_learning_rate: 1e-4
    target: segment.modules.cascaded.fcn_unet.End2End_FCN_Unet
    params:
        concat: False
        image_key: image
        in_channels: 3
        num_classes: 2
        bilinear: True
        base_c: 64
        weight_decay: 1e-4
        losses:
            stage1_loss:
                target: segment.losses.long_tailed.grw_cross_entropy_loss.GRWCrossEntropyLoss
                params:
                    class_weight: ./data/DDR/single_class_weight.txt
                    exp_scale: 0.5
            stage2_loss:
                target: segment.losses.seg.dice_loss.DC_and_CE_loss

dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 4
        num_workers: 0
        train:
            target: segment.dataloader.ddr.DDRSegTrain
            params:
                size: 128
                seg_object: dr_single

        validation:
            target: segment.dataloader.ddr.DDRSegEval
            params:
                size: 128
                seg_object: dr_single
