model:
    base_learning_rate: 1e-4
    target: segment.modules.cascaded.fcn_unet.FCN_Unet
    params:
        ckpt_path: ./experiments/ddr_dr_single_align1_logits_out_res50FCN/18052023_163336/ckpt/ddr_dr_single_align1_logits_out_res50FCN-epoch=237.ckpt        #是stageI的ckpt
        image_key: image
        in_channels: 3
        num_classes: 2
        bilinear: True
        base_c: 64
        weight_decay: 1e-4
        loss:
            target: segment.losses.seg.dice_loss.DC_and_CE_loss

dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 4
        num_workers: 12
        train:
            target: segment.dataloader.ddr.DDRSegTrain
            params:
                size: 512
                seg_object: dr_single

        validation:
            target: segment.dataloader.ddr.DDRSegEval
            params:
                size: 512
                seg_object: dr_single
