model:
    target: segment.modules.long_tailed.disalign.Align_UNet
    params:
        image_key: image
        in_channels: 3
        num_classes: 2
        bilinear: True
        base_c: 64
        weight_decay: 1e-4

        loss:
<<<<<<< HEAD:configs/.ipynb_checkpoints/ddr_dr_single_align_grwCE_unet-checkpoint.yaml
            target: segment.losses.long_tailed.grw_cross_entropy_loss.GRWCrossEntropyLoss
=======
#            target: segment.losses.segmentation.CE_DiceLoss
#            target: segment.losses.long_tailed.grw_cross_entropy_loss.GRWCrossEntropyLoss
            target: segment.losses.long_tailed.grw_cross_entropy_loss.Dice_GRWCrossEntropyLoss
>>>>>>> d448ca6756d5bb1aa69089a05dd1078681e5fedf:configs/ddr_dr_single_align_unet.yaml
            params:
                class_weight: ./data/DDR/single_class_weight.txt


dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 4
        num_workers: 12
        train:
            target: segment.dataloader.ddr.DDRSegTrain
            params:
                size: 768
                seg_object: dr_single

        validation:
            target: segment.dataloader.ddr.DDRSegEval
            params:
                size: 768
                seg_object: dr_single
