model:
    base_learning_rate: 1e-4
    target: segment.modules.fcn.Res50_FCN
    params:
        image_key: image
        in_channels: 3
        num_classes: 2
        weight_decay: 1e-4
        loss:
            target: segment.losses.seg.dice_loss.DC_and_CE_loss


dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 4
        num_workers: 12
        train:
            target: segment.dataloader.ddr.DDRSegTrain
            params:
                size: 1024
                seg_object: dr_single

        validation:
            target: segment.dataloader.ddr.DDRSegEval
            params:
                size: 1024
                seg_object: dr_single
