model:
    base_learning_rate: 1e-4
    target: segment.modules.unet.UNet
    params:
        ckpt_path: ./ckpt/refuge_od_unet-epoch=95.ckpt
        image_key: image
        in_channels: 3
        num_classes: 2
        bilinear: True
        base_c: 64
        weight_decay: 1e-4
        loss:
            target: segment.losses.seg.dice_loss.DC_and_CE_loss


dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 1
        num_workers: 0
        train:
            target: segment.dataloader.gamma.GAMMASegTrain
            params:
                size: 512
                seg_object: od

        validation:
            target: segment.dataloader.gamma.GAMMASegEval
            params:
                size: 512
                seg_object: od
        test:
            target: segment.dataloader.gamma.GAMMASegEval
            params:
                size: 512
                seg_object: od
