model:
    base_learning_rate: 1e-2
    target: classification.modules.resnet.Resnet50
    params:
        image_key: image
        num_classes: 2
        weight_decay: 1e-4
#        loss:
#            target: segment.losses.seg.dice_loss.DC_and_CE_loss

dataset:
    target: classification.dataloader.DataModuleFromConfig
    params:
        batch_size: 8
        num_workers: 16
        train:
            target: classification.dataloader.multi_disease.Multi_diseaseTrain
            params:
                size: 512
                data_csv: data/multi_diease/train.txt
                data_root: data/multi_diease
        validation:
            target: classification.dataloader.multi_disease.Multi_diseaseEval
            params:
                size: 512
                data_csv: data/multi_diease/train.txt
                data_root: data/multi_diease
