model:
    base_learning_rate: 1e-2
    target: classification.modules.resnet.Resnet50
    params:
        image_key: image
        num_classes: 2
        weight_decay: 1e-4
#        loss:
#            target: segment.losses.seg.dice_loss.DC_and_CE_loss

dataset:
    target: classification.dataloader.DataModuleFromConfig
    params:
        batch_size: 8
        num_workers: 16
        train:
            target: classification.dataloader.refuge.REFUGEClassTrain
            params:
                size: 512
                data_csv: data/REFUGE/class_train.txt
                data_root: data/REFUGE
        validation:
            target: classification.dataloader.refuge.REFUGEClassEval
            params:
                size: 512
                data_csv: data/REFUGE/class_eval.txt
                data_root: data/REFUGE
        test:
            target: classification.dataloader.refuge.REFUGEClassTest
            params:
                size: 512
                data_csv: data/REFUGE/class_test.txt
                data_root: data/REFUGE

