model:
    base_learning_rate: 1e-4
    target: classification.modules.resnet.Resnet50
    params:
        image_key: image
        num_classes: 6
        weight_decay: 1e-4
#        loss:
#            target: segment.losses.seg.dice_loss.DC_and_CE_loss

dataset:
    target: classification.dataloader.DataModuleFromConfig
    params:
        batch_size: 16
        num_workers: 0
        train:
            target: classification.dataloader.refuge.REFUGESegTrain
            params:
                size: 128
                data_csv: F:/DL-Data/eyes/glaucoma_OD_OC/REFUGE/refuge_train.txt
                data_root: F:/DL-Data/eyes/glaucoma_OD_OC/REFUGE/images
                segmentation_root: F:/DL-Data/eyes/glaucoma_OD_OC/REFUGE/ground_truths
        validation:
            target: classification.dataloader.refuge.REFUGESegEval
            params:
                size: 128
                data_csv: F:/DL-Data/eyes/glaucoma_OD_OC/REFUGE/refuge_train.txt
                data_root: F:/DL-Data/eyes/glaucoma_OD_OC/REFUGE/images
                segmentation_root: F:/DL-Data/eyes/glaucoma_OD_OC/REFUGE/ground_truths
