model:
    target: segment.modules.long_tailed.disalign.Align_Res50_FCN
    params:
        image_key: image
        in_channels: 3
        num_classes: 2
        weight_decay: 1e-4

        loss:
            target: segment.losses.long_tailed.grw_cross_entropy_loss.GRWCrossEntropyLoss
            params:
                class_weight: ./data/DDR/single_class_weight.txt
                exp_scale: 0.3


dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 4
        num_workers: 12
        train:
            target: segment.dataloader.ddr.DDRSegTrain
            params:
                size: 512
                seg_object: dr_single

        validation:
            target: segment.dataloader.ddr.DDRSegEval
            params:
                size: 512
                seg_object: dr_single
