model:
    base_learning_rate: 1e-4
    target: segment.modules.fcn.Res50_FCN
    params:
        image_key: image
        in_channels: 3
        num_classes: 5
        weight_decay: 1e-4
        loss:
#            target: segment.losses.segmentation.CE_DiceLoss
            target: segment.losses.seg.dice_loss.DC_and_CE_loss


dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 2
        num_workers: 0
        train:
            target: segment.dataloader.ddr.DDRSegTrain
            params:
                size: 128
                seg_object: multi_seg

        validation:
            target: segment.dataloader.ddr.DDRSegEval
            params:
                size: 128
                seg_object: multi_seg
