model:
    target: segment.modules.unet.UNet
    params:
        image_key: image
        in_channels: 3
        num_classes: 2
        bilinear: True
        base_c: 64
        weight_decay: 1e-4

        loss:
#            target: segment.losses.segmentation.CE_DiceLoss
            target: segment.losses.long_tailed.grw_cross_entropy_loss.GRWCrossEntropyLoss
            params:
                class_weight: ./data/DDR/single_class_weight.txt


dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 2
        num_workers: 0
        train:
            target: segment.dataloader.ddr.DDRSegTrain
            params:
                size: 128
                seg_object: dr_single

        validation:
            target: segment.dataloader.ddr.DDRSegEval
            params:
                size: 128
                seg_object: dr_single
