model:
  base_learning_rate: 4.5e-6
  target: segment.modules.vqgan.vqgan.VQModel
  params:
#    ckpt_path: ''
    embed_dim: 256
    n_embed: 1024
    image_key: label
#     ignore_keys: [encoder]
    ddconfig:
      double_z: false
      z_channels: 2048  #这个值必须要与backbone的channels一致
      resolution: 256
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult:
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 32
      dropout: 0.0

    lossconfig:
      target: segment.losses.recon.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 1
        disc_num_layers: 2
        disc_start: 1
        disc_weight: 0.6
        codebook_weight: 1.0

dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 4
        num_workers: 0
        train:
            target: segment.dataloader.idrid.IDRIDSegTrain
            params:
                size: 256
                seg_object: dr_single
                aug: False

        validation:
            target: segment.dataloader.idrid.IDRIDSegEval
            params:
                size: 256
                seg_object: dr_single
                aug: False

