model:
  base_learning_rate: 4.5e-6
  target: segment.modules.vqgan.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 1024
    image_key: label
    ddconfig:
      double_z: false
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

    lossconfig:
      target: segment.losses.recon.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 0
        disc_weight: 0.75
        codebook_weight: 1.0

dataset:
    target: segment.dataloader.DataModuleFromConfig
    params:
        batch_size: 2
        num_workers: 0
        train:
            target: segment.dataloader.idrid.IDRIDSegTrain
            params:
                size: 128
                seg_object: dr_single
                aug: False

        validation:
            target: segment.dataloader.idrid.IDRIDSegEval
            params:
                size: 128
                seg_object: dr_single
                aug: False

